### ISSUE TITLE
MinAddon AuroraServices addon.d

### ISSUE THREAD

**Issue by biladina** [FriendlyNeighborhoodShane/MinMicroG-abuse-github#3]
hi, is MinAddon AuroraServices not having an addon.d script??
I am using only MinAddon AuroraServices (without MinMicroG) from 13 May build, and after I updated my ROM, the AuroraServices is gone and I have to install it again..

**Comment by FriendlyNeighborhoodShane** [comment]
Yeah it doesn't have an addon.d, it's mostly a demo zip.

For most cases I'd just recommend the flashable zips that come with the AuroraServices releases themselves: https://gitlab.com/AuroraOSS/AuroraServices/-/tags/1.1.1

**Comment by biladina** [comment]
> Yeah it doesn't have an addon.d, it's mostly a demo zip.
> 
> For most cases I'd just recommend the flashable zips that come with the AuroraServices releases themselves: https://gitlab.com/AuroraOSS/AuroraServices/-/tags/1.1.1

hi, the problem is the original installer broken long ago, can't install in new android version, even when I create this issue, the original installer already broken, and till now there is no update on the original installer..

please consider to add addon.d to aurora services.. thank you..
