### ISSUE TITLE
Android 13 Support?

### ISSUE THREAD

**Issue by Milor123** [FriendlyNeighborhoodShane/MinMicroG-abuse-github#4]
Hi guys, I would like know if it support android 13? I want do upgrade to A13 From A12.

**Comment by FriendlyNeighborhoodShane** [comment]
The latest CI build has been known to work on A13, yes, but like for anything in android modding, nothing can be said about the endless possible configurations of any device. It never hurts to have a backup handy.

**Comment by Milor123** [comment]
Thank you very much bro !!
