### ISSUE TITLE
Module Version Information

### ISSUE THREAD

**Issue by moya2162** [FriendlyNeighborhoodShane/MinMicroG-abuse-github#8]
Would it be possible during the automatic build to have module.prop have version and versionCode be populated with the build date? This would be nice to have to simply know which version is currently installed when viewed in the modules tab in Magisk.

Example module.prop:
```
id=MinMicroG
name=Minimal MicroG Pack MinimalIAP Edition
version=20230918004218
versionCode=20230918004218
author=MOVZX and FatherJony and FriendlyNeighborhoodShane
description=A Minimal MicroG installer with just the essentials
support=
donate=
minMagisk=1900
```

**Comment by FriendlyNeighborhoodShane** [comment]
Hi, sorry for the late reply.

That's a good idea.

**Comment by FriendlyNeighborhoodShane** [comment]
Done.
